export enum SocketEvent {
  Tournament = "tournament",
  Ping = "ping",
  JoinRoom = "joinRoom",
  SetRoom = "setRoom",
  LeaveRoom = "leaveRoom",
  Error = "error",
  Notify = "notif",
  Log = "log",
  Matches = "matches",
  SetMatch = "setMatch",
  Participants = "participants",
  SetParticipant = "setParticipant",
  SetLive = "setLive",
  VetoMapPick = "vetoMapPick",
  VetoSidePick = "vetoSidePick",
  VetoSettings = "vetoSettings",
  VetoRequestCredentials = "vetoRequestCredentials",
  VetoRequestCredentialsResponse = "vetoRequestCredentialsResponse",
}
